on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: release all os — mac signed & notarized, windows, linux

permissions:
  contents: write # Required to create releases and upload assets

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create GitHub Release (draft)
        id: create_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${{ github.ref_name }}"
          echo "Ensuring draft release for tag: $tag"
          if gh release view "$tag" >/dev/null 2>&1; then
            echo "Release $tag already exists, skipping creation"
          else
            gh release create "$tag" \
              --title "$tag" \
              --draft \
              --notes ""
          fi

  release:
    name: Release (${{ matrix.build_name }})
    needs: create-release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            build_name: linux-x64
            build_command: pnpm build:linux
            artifact_name: 'dist/{*.AppImage,*.rpm,*.deb,*.yml}'
          - os: ubuntu-latest
            platform: linux
            build_name: linux-arm64
            build_command: pnpm build:linux:arm64
            artifact_name: 'dist/{*.AppImage,*.rpm,*.deb,*.yml}'
          - os: ubuntu-latest
            platform: linux
            build_name: linux-arm32
            build_command: pnpm build:linux:armv7l
            artifact_name: 'dist/{*.AppImage,*.rpm,*.deb,*.yml}'
          - os: windows-latest
            platform: windows
            build_name: windows-amd64
            build_command: pnpm build:win
            artifact_name: 'dist/{*.msi,*.exe,*.blockmap,*.yml}'
          - os: windows-latest
            platform: windows
            build_name: windows-amd32
            build_command: pnpm build:win:ia32
            artifact_name: 'dist/{*.msi,*.exe,*.blockmap,*.yml}'
          - os: windows-latest
            platform: windows
            build_name: windows-arm64
            build_command: pnpm build:win:arm64
            artifact_name: 'dist/{*.msi,*.exe,*.blockmap,*.yml}'
          - os: macos-latest
            platform: macos
            build_name: macos-arm64
            build_command: pnpm build:mac:arm64
            artifact_name: 'dist/{*.dmg,*.blockmap,*.yml}'
          - os: macos-13
            platform: macos
            build_name: macos-intel
            build_command: pnpm build:mac:x64
            artifact_name: 'dist/{*.dmg,*.blockmap,*.yml}'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '23'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: pnpm install in ./src/client-viewer
        run: |
          cd ./src/client-viewer
          pnpm install

      - name: pnpm install in ./
        run: pnpm install

      - name: Install Linux build dependencies
        if: ${{ matrix.platform == 'linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2

      - name: Create .env file for client-viewer with Google Analytics tag (macOS)
        if: ${{ matrix.platform == 'macos' }}
        run: |
          echo "VITE_CLIENT_VIEWER_GA_TAG=${{ secrets.CLIENT_VIEWER_GA_TAG_MACOS }}" > ./src/client-viewer/.env

      - name: Create .env file for client-viewer with Google Analytics tag (Windows)
        if: ${{ matrix.platform == 'windows' }}
        run: |
          echo "VITE_CLIENT_VIEWER_GA_TAG=${{ secrets.CLIENT_VIEWER_GA_TAG_WINDOWS }}" > ./src/client-viewer/.env

      - name: Create .env file for client-viewer with Google Analytics tag (Linux)
        if: ${{ matrix.platform == 'linux' }}
        run: |
          echo "VITE_CLIENT_VIEWER_GA_TAG=${{ secrets.CLIENT_VIEWER_GA_TAG_LINUX }}" > ./src/client-viewer/.env

      - name: pnpm build on Windows
        if: ${{ matrix.platform == 'windows' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ${{ matrix.build_command }}

      - name: pnpm build on macOS
        if: ${{ matrix.platform == 'macos' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # certificate for signing (base64-encoded .p12) and its password
          CSC_LINK: ${{ secrets.MAC_CERTS }}
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTS_PASSWORD }}
        run: ${{ matrix.build_command }}

      - name: pnpm build on Linux
        if: ${{ matrix.platform == 'linux' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ${{ matrix.build_command }}

      - name: Rename Linux update manifest for non-x64
        if: ${{ matrix.platform == 'linux' }}
        run: |
          if [ -f dist/latest-linux.yml ]; then
            mv dist/latest-linux.yml dist/latest-${{ matrix.build_name }}.yml
          fi

      - name: Rename Windows update manifest for non-x64
        if: ${{ matrix.platform == 'windows' }}
        shell: pwsh
        run: |
          $manifest = Join-Path dist 'latest.yml'
          if (Test-Path $manifest) {
            Rename-Item $manifest "latest-${{ matrix.build_name }}.yml"
          }

      - name: Rename macOS update manifest for arm builds
        if: ${{ matrix.platform == 'macos' }}
        run: |
          if [ -f dist/latest-mac.yml ]; then
            mv dist/latest-mac.yml dist/latest-${{ matrix.build_name }}.yml
          fi

      - name: Notarize and staple macOS DMG
        if: ${{ matrix.platform == 'macos' }}
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          shopt -s nullglob
          for dmg in dist/*.dmg; do
            echo "Submitting $dmg for notarization"
            xcrun notarytool submit "$dmg" \
              --apple-id "$APPLE_ID" \
              --team-id "$APPLE_TEAM_ID" \
              --password "$APPLE_APP_SPECIFIC_PASSWORD" \
              --wait
            echo "Stapling ticket to $dmg"
            xcrun stapler staple "$dmg"
          done

      - name: Upload binaries to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ matrix.artifact_name }}
          tags: true
          draft: true
